#!/usr/bin/env bash

tnl-grid-setup --dimensions 2 \
               --origin-x 0.0 \
               --origin-y 0.0 \
               --proportions-x 1.0 \
               --proportions-y 1.0 \
               --size-x 100 \
               --size-y 100

tnl-init --test-function sin-wave \
         --output-file init.tnl
tnl-euler-2d --discontinuity-placement-0 0.3 \
             --discontinuity-placement-1 0.3 \
             --discontinuity-placement-2 0.3 \
             --left-density 1.0 \
             --right-density 1.0 \
             --left-velocity-0 -2.0 \
             --left-velocity-1 -2.0 \
             --left-velocity-2 -2.0 \
             --right-velocity-0 2.0 \
             --right-velocity-1 2.0 \
             --right-velocity-2 2.0 \
             --left-pressure 0.4 \
             --right-pressure 0.4 \
             --time-discretisation explicit \
             --boundary-conditions-constant 0 \
             --discrete-solver merson \
             --snapshot-period 0.01 \
             --final-time 1.0

tnl-view --mesh mesh.tnl --input-files *tnl     
