#!/bin/bash

INSTALL_PREFIX=${HOME}/local

CPUS=`grep -c processor /proc/cpuinfo`

echo "Building TNL using $CPUS processors."

if [ ! -d Debug ];
then
   mkdir Debug
fi
if [ ! -d Release ];
then
   mkdir Release
fi

cd Debug
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${HOME}/local -DCUDA_ARCHITECTURE=1.2 -DWITH_CUDA=no
make -j${CPUS} #VERBOSE=1
make -j${CPUS} test
make -j${CPUS} install

cd ../Release
cmake .. -DCMAKE_INSTALL_PREFIX=${HOME}/local -DCUDA_ARCHITECTURE=1.2 -DWITH_CUDA=no
make -j${CPUS} #VERBOSE=1
make -j${CPUS} test
make -j${CPUS} install
