#!/bin/bash

INSTALL_PREFIX=${HOME}/local
WITH_CUDA=no
CUDA_ARCHITECTURE=2.0
VERBOSE=0

CPUS=`grep -c processor /proc/cpuinfo`

echo "Building TNL using $CPUS processors."

if [ ! -d Debug ];
then
   mkdir Debug
fi
if [ ! -d Release ];
then
   mkdir Release
fi

cd Debug
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${HOME}/local -DCUDA_ARCHITECTURE=${CUDA_ARCHITECTURE} -DWITH_CUDA=${WITH_CUDA}
make -j${CPUS} VERBOSE=${VERBOSE}
make -j${CPUS} test
make -j${CPUS} install

cd ../Release
cmake .. -DCMAKE_INSTALL_PREFIX=${HOME}/local -DCUDA_ARCHITECTURE=${CUDA_ARCHITECTURE} -DWITH_CUDA=${WITH_CUDA}
make -j${CPUS} VERBOSE=${VERBOSE}
make -j${CPUS} test
make -j${CPUS} install
