#!/bin/bash

PREFIX=${HOME}/.local
INSTALL="yes"


for option in "$@"
do
   case $option in
      --prefix=*                       ) PREFIX="${option#*=}" ;;
      --install=*                      ) INSTALL="${option#*=}" ;;
   esac
done

doxygen

if [[ "$INSTALL" == "yes" ]]; then
   mkdir -p ${PREFIX}/share/doc/tnl
   cp -r Documentation/* ${PREFIX}/share/doc/tnl
fi

