#!/bin/bash

INSTALL_PREFIX=${HOME}/.local
BUILD_RELEASE=yes
BUILD_DEBUG=yes
#VERBOSE="VERBOSE=1"

for option in "$@"
do
    case $option in
        --no-debug                    ) BUILD_DEBUG="no" ;;
        --no-release                  ) BUILD_RELEASE="no" ;;        
        *                             ) OPTIONS="${OPTIONS} ${option}" ;;
    esac
done

if test ${BUILD_DEBUG} = "yes";
then
    if [ ! -d Debug ];
    then
       mkdir Debug
    fi
    cd Debug
    if ! ../build --root-dir=.. --build=Debug --install=yes ${OPTIONS}
    then
       exit 1
    fi
    cd ..
fi

if [ ! -d Release ];
then
    if [ ! -d Release ];
    then
       mkdir Release
    fi
    cd Release
    if ! ../build --root-dir=.. --build=Release --install=yes ${OPTIONS};
    then
        exit 1
    fi
    cd ..
fi

TNL_TEST=`which tnl-bindir`

if test x${TNL_TEST} = x;
then
    echo ""
    echo "WARNING !!!"
    echo ""
    echo "Your system does not see TNL which was installed right now."
    echo "You need to add it to your system variables PATH and LD_LIBRARY_PATH."
    echo "Add the following to your .bashrc file:"
    echo ""
    
    echo "if test x\${PATH} = x;"
    echo "then"
    echo "   PATH=${PREFIX}/bin"
    echo "else"
    echo "   PATH=\${PATH}:${PREFIX}/bin"
    echo "fi"
    echo "if test x\${LD_LIBRARY_PATH} = x;"
    echo "then"
    echo "   LD_LIBRARY_PATH=${PREFIX}/lib"
    echo "else"
    echo "   LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${PREFIX}/lib"
    echo "fi"
    echo "export PATH"
    echo "export LD_LIBRARY_PATH"
fi

exit 0
