// This file is generated by the ./configure script. Do not change it!

#define CONFIG_DESCRIPTION_FILE "/home/oberhuber/local/share/tnldist-0.2/sdf-restore.cfg.desc"

#define CPP_COMPILER_NAME "g++"
