#!/bin/bash

device="host"
dimensions="1D" # 2D 3D"
sizes1D="16" # 32 64 128 256 512"
sizes2D="16 32 64 128 256 512"
sizes3D="16 32 64 128"
testFunctions="exp-bump"
snapshotPeriod=0.1
finalTime=1
timeDependence="linear"
solverName="tnl-heat-equation-eoc-test"

setupTestFunction()
{
   testFunction=$1
   if test x${testFunction} = "xexp-bump";
   then
      origin=-1.0
      proportions=2.0
      amplitude=1.0
      waveLength=1.0
      waveLengthX=1.0
      waveLengthY=1.0
      waveLengthZ=1.0
      wavesNumber=0.0
      wavesNumberX=0.0
      wavesNumberY=0.0
      wavesNumberZ=0.0
      phase=0.0
      phaseX=0.0
      phaseY=0.0
      phaseZ=0.0
      sigma=0.5
   fi
}

setupGrid()
{
   dimensions=$1
   gridSize=$2
   tnl-grid-setup --dimensions ${dimensions} \
                  --origin-x ${origin} \
                  --origin-y ${origin} \
                  --origin-z ${origin} \
                  --proportions-x ${proportions} \
                  --proportions-y ${proportions} \
                  --proportions-z ${proportions} \
                  --size-x ${gridSize} \
                  --size-y ${gridSize} \
                  --size-z ${gridSize} 
}

setInitialCondition()
{
   testFunction=$1
   tnl-init --function ${testFunction} \
            --output-file exact-u.tnl \
            --amplitude ${amplitude} \
            --wave-length ${waveLength} \
            --wave-length-x ${waveLengthX} \
            --wave-length-y ${waveLengthY} \
            --wave-length-z ${waveLengthZ} \
            --waves-number ${wavesNumber} \
            --waves-number-x ${wavesNumberX} \
            --waves-number-y ${wavesNumberY} \
            --waves-number-z ${wavesNumberZ} \
            --phase ${phase} \
            --phase-x ${phaseX} \
            --phase-y ${phaseY} \
            --phase-z ${phaseZ} \
            --sigma ${sigma} \
            --test-function-time-dependence ${timeDependence} \
            --snapshot-period ${snapshotPeriod} \
            --final-time ${finalTime}
}

solve()
{
   timeDiscretisation=$1
   discreteSolver=$2
   ${solverName} --mesh mesh.tnl \
                 --initial-condition exact-u-0000.tnl \
                 --time-discretisation ${timeDiscretisation} \
                 --discrete-solver ${discreteSolver} \
                 --test-function ${testFunction}\
                 --amplitude ${amplitude} \
                 --wave-length ${waveLength} \
                 --wave-length-x ${waveLengthX} \
                 --wave-length-y ${waveLengthY} \
                 --wave-length-z ${waveLengthZ} \
                 --waves-number ${wavesNumber} \
                 --waves-number-x ${wavesNumberX} \
                 --waves-number-y ${wavesNumberY} \
                 --waves-number-z ${wavesNumberZ} \
                 --phase ${phase} \
                 --phase-x ${phaseX} \
                 --phase-y ${phaseY} \
                 --phase-z ${phaseZ} \
                 --sigma ${sigma} \
                 --test-function-time-dependence ${timeDependence} \
                 --snapshot-period ${snapshotPeriod} \
                 --final-time ${finalTime}
}
               
computeError()
{

   tnl-diff --mesh mesh.tnl \
            --input-files numericalSolution-*.tnl analyticSolution-*.tnl \
            --mode halves \
            --output-file ${dofSize}-dofs 
}

runTest()
{
   for testFunction in ${testFunctions};
   do
      mkdir -p ${testFunction}
      cd ${testFunction}
      setupTestFunction ${testFunction}
      
      for dim in ${dimensions};
      do
         mkdir -p $dim
         cd ${dim}
         if test $dim = 1D;
         then 
            sizes=$sizes1D
         fi
         if test $dim = 2D;
         then 
            sizes=$sizes2D
         fi
         if test $dim = 3D;
         then 
            sizes=$sizes3D
         fi
         
         for size in $sizes;
         do
            mkdir -p $size
            cd $size
               if test ! -f computation-done;
               then
                  touch computation-in-progress
                  setupGrid $dim $size 
                  setInitialCondition $testFunction
                  solve explicit merson
                  mv computation-in-progress computation-done
               fi
            cd ..
         done

         cd ..
      done
      cd ..
   done
}

runTest

