#!/usr/bin/env bash

BASE="ftp://math.nist.gov/pub/MatrixMarket2/Harwell-Boeing/"
                
PWD=`pwd`
IWD="$PWD"
DEBUG="no"
MATRIX_FORMATS_TEST="$IWD/matrix-formats-test-dbg"
MATRIX_FORMATS_TEST_DBG="$IWD/.libs/lt-matrix-formats-test-dbg"

source ../tnl-env-variables
source $TNL_SOURCE_DIR/tests/matrix-market
source $TNL_SOURCE_DIR/tests/florida-matrix-market
export TNL_SPARSE_MATRIX_CHECK_CFG_DESC_FILE="$TNL_SOURCE_DIR/tests/tnl-sparse-matrix-check.cfg.desc"

#MM_MATRICES="ftp://math.nist.gov/pub/MatrixMarket2/Harwell-Boeing/bcsstruc4/bcsstm27.mtx.gz"
#FLORIDA_MM_MATRICES=""

run_test()
{
   if test x$DEBUG == xyes;
   then
      rm .gdbinit
      echo  "file $MATRIX_FORMATS_TEST_DBG" > .gdbinit
      echo "" >> .gdbinit
      echo -n "run $@" >> .gdbinit
      gdb
   else
      $MATRIX_FORMATS_TEST $@
   fi
}

echo "+---------------------------------------------------------------------------------------------------+------------+-------------+-------------+-------------+-------------+-------------+" > matrix-formats-test.log
echo "| Testing matrix                                                                                    | Full.Mat.  | CSR x FULL  | CSR x COA   |CSRxCUDA COA |CSR x FastCSR|CSR x CoaFCSR|" >> matrix-formats-test.log
echo "+---------------------------------------------------------------------------------------------------+------------+-------------+-------------+-------------+-------------+-------------+" >> matrix-formats-test.log

for link in $MM_MATRICES;
do
   echo "*******************************************************************************"
   matrix=matrices`echo $link | sed 's/ftp:\/\/math.nist.gov\/pub//'`
   unzipped_matrix=`echo $matrix | sed 's/.gz//'`
   if test ! -e $matrix;
   then
      echo "Matrix $matrix is missing !!! Run the script 'get-matrices' first."
      echo "Matrix $matrix is missing !!! Run the script 'get-matrices' first." >> matrix-formats-test.log            
   else
      if test ! -e $unzipped_matrix.float.bin.bz2;
      then
         echo "Missing $unzipped_matrix.float.bin.bz2 !!! Run the script 'convert-matrices'."
         echo "Missing $unzipped_matrix.float.bin.bz2 !!! Run the script 'convert-matrices'."  >> matrix-formats-test.log
      else
         gunzip -f $matrix
         echo "Checking with the matrix $unzipped_matrix in single precision ..."
         run_test --input-file $unzipped_matrix.float.bin.bz2 --input-mtx-file $unzipped_matrix --log-file matrix-formats-test.log --verbose 1
         gzip $unzipped_matrix
      fi    
      echo "-------------------------------------------------------------------------------"
      if test ! -e $unzipped_matrix.double.bin.bz2;
      then
         echo "Missing $unzipped_matrix.double.bin.bz2 !!! Run the script 'convert-matrices'."
         echo "Missing $unzipped_matrix.double.bin.bz2 !!! Run the script 'convert-matrices'."  >> matrix-formats-test.log
      else
         gunzip -f $matrix
         echo "Checking with the matrix $unzipped_matrix in double precison ..." 
         run_test --input-file $unzipped_matrix.double.bin.bz2 --input-mtx-file $unzipped_matrix --log-file matrix-formats-test.log --verbose 1
         gzip $unzipped_matrix
      fi      
   fi
done

for link in $FLORIDA_MM_MATRICES;
do
   matrix=matrices`echo $link | sed 's/http:\/\/www.cise.ufl.edu\/research\/sparse//'`
   if test ! -e $matrix;
   then      
      echo "Matrix $matrix is missing !!! Run the script 'get-matrices' first."
      echo "Matrix $matrix is missing !!! Run the script 'get-matrices' first." >> matrix-formats-test.log
   else
     DIRNAME=`dirname $matrix`
     FILENAME=`basename $matrix`
     cd $DIRNAME
     tar zxvf $FILENAME
     cd $IWD
     SUBDIRNAME=`echo $FILENAME | sed 's/.tar.gz//'`
     rm -f $DIRNAME/$SUBDIRNAME/*_b.mtx # these are usualy in array format
     for file in $DIRNAME/$SUBDIRNAME/*.mtx;
     do
         echo "###############################################################################"
         if test ! -e $file.float.bin.bz2;
         then
            echo "Missing $file.float.bin.bz2 !!! Run the script 'convert-matrices'."
            echo "Missing $file.float.bin.bz2 !!! Run the script 'convert-matrices'." >> matrix-formats-test.log
         else   
            echo "Checking with the matrix $file ..."
            run_test --input-file $file.float.bin.bz2 --input-mtx-file $file --log-file matrix-formats-test.log --verbose 1                        
         fi
         if test ! -e $file.double.bin.bz2;
         then
            echo "Missing $file.double.bin.bz2 !!! Run the script 'convert-matrices'."
            echo "Missing $file.double.bin.bz2 !!! Run the script 'convert-matrices'." >> matrix-formats-test.log
         else   
            echo "Checking with the matrix $file ..."
            run_test --input-file $file.double.bin.bz2 --input-mtx-file $file --log-file matrix-formats-test.log --verbose 1
         fi 
         rm $file                          
      done
   fi
done
