#!/usr/bin/env bash

BASE="ftp://math.nist.gov/pub/MatrixMarket2/Harwell-Boeing/"
                
PWD=`pwd`
TNL_SPARSE_MATRIX_CHECK="$PWD/tnl-sparse-matrix-check"
IWD="$PWD"

source ../tnl-env-variables
source $TNL_SOURCE_DIR/tests/florida-matrix-market
source $TNL_SOURCE_DIR/tests/matrix-market
export TNL_SPARSE_MATRIX_CHECK_CFG_DESC_FILE="$TNL_SOURCE_DIR/tests/tnl-sparse-matrix-check.cfg.desc"

#MM_MATRICES=""
FLORIDA_MM_MATRICES=""

#./tnl-sparse-matrix-check-dbg --input-file matrices/MatrixMarket2/misc/cylshell/s3dkq4m2.mtx
#exit

echo " +-----------------------------------------------+---------+--------------+--------------+-----------+--------------+ " > sparse-matrix-check.log
echo " | Matrix name (by Matrix Market)                |    Size |  NonZeroEls. |       GFLOPS | Art.Zer. %|CoaCSR.GFLOPS | " >> sparse-matrix-check.log
echo " +-----------------------------------------------+---------+--------------+--------------+-----------+--------------+ " >> sparse-matrix-check.log

for link in $MM_MATRICES;
do
   matrix=matrices`echo $link | sed 's/ftp:\/\/math.nist.gov\/pub//'`
   unzipped_matrix=`echo $matrix | sed 's/.gz//'`
   tnl_matrix=$unzipped_matrix.bin
   if test ! -e $tnl_matrix.bz2;
   then
      if test ! -e $matrix;
      then
         echo "Getting $matrix ..."      
         wget -x --cut-dirs=1 -P matrices -nH $link
      fi
      echo "Converting $matrix ..."
      gunzip -f $matrix
      #tnl-matrix-convert --input-file $unzipped_matrix --output-file $tnl_matrix --verbose yes --verify yes
      ./tnl-sparse-matrix-check --input-file $unzipped_matrix --log-file sparse-matrix-check.log
      gzip $unzipped_matrix
   fi
   
   #echo ""
done

echo " +-----------------------------------------------+---------+--------------+--------------+-----------+--------------+ " >> sparse-matrix-check.log
echo " | Matrix name ( by Uni.of Florida Sp.Mat.Col. ) |    Size |  NonZeroEls. |       GFLOPS | Art.Zer. %|CoaCSR.GFLOPS | " >> sparse-matrix-check.log
echo " +-----------------------------------------------+---------+--------------+--------------+-----------+--------------+ " >> sparse-matrix-check.log


for link in $FLORIDA_MM_MATRICES;
do
   matrix=matrices`echo $link | sed 's/http:\/\/www.cise.ufl.edu\/research\/sparse//'`
   if test ! -e $matrix;
   then
      echo "Getting $matrix ..."      
      wget -x --cut-dirs=2 -P matrices -nH $link
   fi
   DIRNAME=`dirname $matrix`
   FILENAME=`basename $matrix`
   cd $DIRNAME
   tar zxvf $FILENAME
   cd $IWD
   
   SUBDIRNAME=`echo $FILENAME | sed 's/.tar.gz//'`
   
   for file in $DIRNAME/$SUBDIRNAME/*.mtx;
   do
      tnl_matrix=$file.bin
      if test ! -e $tnl_matrix.bz2;
      then
         echo "Converting matrix $file ..."
         tnl-matrix-convert --input-file $file --output-file $tnl_matrix --verbose yes --verify yes 
      fi
   done
   
   #      $TNL_SPARSE_MATRIX_CHECK --input-file $files --log-file sparse-matrix-check.log
done
