#!/usr/bin/env bash

tnl-grid-setup --dimensions 2 \
               --origin-x 0.0 \
               --origin-x 0.0 \
               --proportions-x 1.0 \
               --proportions-y 1.0 \
               --size-x 100 \
               --size-y 100 
 
tnl-init --test-function heaviside-of-paraboloid \
         --output-file init.tnl \
         --x-center 0.5 \
         --y-center 0.5 \
         --z-center 0.5 \
         --radius 0.1

tnl-advection-dbg --initial-condition init.tnl \
                  --time-discretisation explicit \
                  --time-step 1.0e-5 \
                  --boundary-conditions-constant 1.0 \
                  --discrete-solver euler \
                  --snapshot-period 0.1 \
                  --final-time 1.0 \
                  --artifical-viscosity 1.0 \
	          --begin sin_square \
	          --advection-speedX 2.0 \

tnl-view --mesh mesh.tnl --input-files *tnl     
