SOURCES +=

HEADERS += config.h \
           information.h \
           mesh.h \
           traversal.h \
           common/common.h \
           config/config_base.h \
           config/hexahedral.h \
           config/linear.h \
           config/quadrilateral.h \
           config/tetrahedral.h \
           config/triangular.h \
           config/triangular_noedges.h \
           detail/container.h \
           detail/id.h \
           detail/mesh_entity.h \
           detail/mesh_entity_border.h \
           detail/mesh_entity_coborder.h \
           detail/mesh_entity_key.h \
           detail/mesh_initializer.h \
           detail/mesh_layer.h \
           detail/mesh_pointer.h \
           detail/mesh_tags.h \
           detail/point.h \
           detail/range.h \
           global/array.h \
           global/static_array.h \
           global/static_assert.h \
           global/static_if.h \
           global/static_loop.h \
           global/static_switch.h \
           io/io.h \
           io/io_base.h \
           io/netgen_neutral.h \
           io/petr_bauer.h \
           io/vtk_legacy.h \
           topology/edge.h \
           topology/hexahedron.h \
           topology/quadrilateral.h \
           topology/tetrahedron.h \
           topology/topology.h \
           topology/triangle.h \
           topology/vertex.h \
