#!/bin/bash

# exit as soon as there is an error
set -e

PREFIX=${HOME}/.local
for option in "$@"; do
    case $option in
        --prefix=*) PREFIX="${option#*=}" ;;
    esac
done

pkgname=tinyxml2
pkgver=9.0.0
url="https://github.com/leethomason/$pkgname/archive/$pkgver/$pkgname-$pkgver.tar.gz"
sha256sum='cc2f1417c308b1f6acc54f88eb70771a0bf65f76282ce5c40e54cfe52952702c'

# prepare
mkdir -p "build-$pkgname"
pushd "build-$pkgname"

if [[ ! -f "$pkgver.tar.gz" ]]; then
   curl -gqb "" -fLC - --retry 3 --retry-delay 3 -o "$pkgver.tar.gz" "$url"
fi
echo -e "$sha256sum\t$pkgver.tar.gz" > "$pkgname.checksum"
sha256sum --check "$pkgname.checksum"
tar -xf "$pkgver.tar.gz"

# build and install
cmake ./$pkgname-$pkgver \
   -DCMAKE_INSTALL_PREFIX="$PREFIX" \
   -DCMAKE_INSTALL_LIBDIR=lib \
   -DCMAKE_BUILD_TYPE=Release
make
make install
