#!/bin/bash

set -e

# compile the tests
[[ ! -d Debug ]] && mkdir Debug
pushd Debug
../build --root-dir=.. --build=Debug \
         --with-examples=no --with-benchmarks=no --with-tools=no --with-python=no --with-doc=no \
         --with-tests=yes --run-tests=no \
         --with-clang=yes --with-cuda=yes --with-coverage=yes
popd

tests=(
#   AllocatorsTest-dbg  # FIXME: CUDA
   AssertTest-dbg
#   AssertCudaTest-dbg  # FIXME: CUDA
   FileNameTest-dbg
#   FileTest-dbg  # FIXME: CUDA
   ObjectTest-dbg
#   ParallelForTest-dbg  # FIXME: CUDA
   StringTest-dbg
   TimerTest-dbg

   # Containers
#   ArrayOperationsTest-dbg  # FIXME: CUDA
   ArrayTest-dbg
#   ArrayTestCuda-dbg  # FIXME: CUDA
   ArrayViewTest-dbg
   VectorTest-dbg
   VectorPrefixSumTest-dbg
   VectorEvaluateAndReduceTest-dbg
   VectorBinaryOperationsTest-dbg
   VectorUnaryOperationsTest-dbg
   StaticArrayTest-dbg
   StaticVectorTest-dbg
   StaticVectorOperationsTest-dbg
   ListTest-dbg
#   MultireductionTest-dbg  # FIXME: CUDA
   MultimapTest-dbg
   StaticMultimapTest-dbg
   # TODO: run these with mpirun (coverage.py does not support that)
   DistributedArrayTest-dbg
   DistributedVectorBinaryOperationsTest-dbg
   DistributedVectorUnaryOperationsTest-dbg

   # Functions
#   BoundaryMeshFunctionTest-dbg  # FIXME: CUDA
#   MeshFunctionTest-dbg  # FIXME: CUDA

   # Matrices
#   DenseMatrixTest-dbg  # FIXME: CUDA
#   SparseMatrixCopyTest-dbg  # FIXME: CUDA
#   SparseMatrixTest_AdEllpack-dbg  # FIXME: CUDA
#   SparseMatrixTest_BiEllpack-dbg  # FIXME: CUDA
#   SparseMatrixTest_ChunkedEllpack-dbg  # FIXME: CUDA
#   SparseMatrixTest_CSR-dbg  # FIXME: CUDA
#   SparseMatrixTest_Ellpack-dbg  # FIXME: CUDA
#   SparseMatrixTest_SlicedEllpack-dbg  # FIXME: CUDA

   # Meshes
   BoundaryTagsTest-dbg
#   MeshEntityTest-dbg
#   MeshOrderingTest-dbg
#   MeshReaderTest-dbg
#   MeshTest-dbg
)

# run the programs and create coverage reports
./scripts/code_coverage/coverage.py -b Debug -o coverage_report/ ${tests[@]}
