#!/usr/bin/env python

class timeSerie:
   def __init__( self, index, label ):
      self.index = index
      self.label = label

inputFile = ""
outputFile = ""
verbose = "false"
timeSeries = []

i = 0
while i < len( arguments ):
   if arguments[ i ] == "--input-file":
      refinement = arguments[ i + 1 ]
      i = i + 2
      continue
   if arguments[ i ] == "--output-file":
      output_file_name = arguments[ i + 1 ]
      i = i + 2
      continue
   if arguments[ i ] == "--time-serie":
      index = arguments[ i + 1 ]
      label = arguments[ i + 2 ]
      timeSeries.append( timeSerie( index, label ) )
      i = i + 3
      continue
   if arguments[ i ] == "--verbose":
       verbose = float( arguments[ i + 1 ] )
       i = i +2
       continue       
   input_files. append( arguments[ i ] )
   i = i + 1
   

